/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function fingerprintDiff(pngInput: string | Buffer, options?: JsEqualityFingerprintOptions | undefined | null): Promise<unknown>

export interface JsEqualityFingerprintOptions {
  redThreshold?: JsRedThreshold
  dilateRadius?: number
  gridSize?: number
  densityThresholds?: Array<number>
  padToSquare?: boolean
}

export interface JsRedThreshold {
  rMin?: number
  gMax?: number
  bMax?: number
  aMin?: number
}
